name: Build and release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: yarn install --frozen-lockfile
        working-directory: spookfox-addon

      - run: echo "${{secrets.CHROME_PRIVATE_KEY}} > key.pem"
        working-directory: spookfox-addon

      - run: yarn build
        working-directory: spookfox-addon

      - run: yarn publish:ff-unlisted
        working-directory: spookfox-addon
        env:
          FIREFOX_ADDON_KEY: "${{ secrets.FIREFOX_ADDON_KEY }}"
          FIREFOX_ADDON_SECRET: "${{ secrets.FIREFOX_ADDON_SECRET }}"

      - run: mv ./addons-dist/*.xpi ./addons-dist/spookfox-ff.xpi
        working-directory: spookfox-addon

      - run: mv ./addons-dist/*.crx ./addons-dist/spookfox-chrome.crx
        working-directory: spookfox-addon

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./spookfox-addon/addons-dist/spookfox-ff.xpi
            ./spookfox-addon/addons-dist/spookfox-chrome.crx
