name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish_firefox_addon:
    name: Build and publish Firefox addon
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: yarn
        working-directory: spookfox-addon

      - run: yarn publish-addon
        working-directory: spookfox-addon
        env:
          FIREFOX_ADDON_KEY: "${{ secrets.FIREFOX_ADDON_KEY }}"
          FIREFOX_ADDON_SECRET: "${{ secrets.FIREFOX_ADDON_SECRET }}"

      - uses: actions/upload-artifact@v2
        with:
          name: spookfox-addon
          path: spookfox-addon/dist/addons/*.xpi

  release:
    name: Create a release
    runs-on: ubuntu-latest
    needs:
      - publish_firefox_addon
    steps:
      - uses: actions/download-artifact@v3
        name: Download spookfox-addon
        with:
          path: ./release

      - run: mv ./release/spookfox-addon/*.xpi ./release/spookfox-firefox.xpi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/spookfox-firefox.xpi
