name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish_firefox_addon:
    name: Build and publish Firefox addon
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: yarn
        working-directory: spookfox-addon

      - run: yarn build-addon
        working-directory: spookfox-addon
        env:
          FIREFOX_ADDON_KEY: "${{ secrets.FIREFOX_ADDON_KEY }}"
          FIREFOX_ADDON_SECRET: "${{ secrets.FIREFOX_ADDON_SECRET }}"

      - uses: actions/upload-artifact@v2
        with:
          name: spookfox-addon
          path: spookfox-addon/dist/addons/
